# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Şükrü Ozan, Ph.D.
title: Vice Chairman, R&D Center Director
email: sukruozan@gmail.com
website: http://www.sukruozan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sukruozan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sukruozan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Şükrü Ozan @ AdresGezgini Inc.
  icon: fas fa-globe
  url: https://www.adresgezgini.com/ekibimiz/sukru-ozan
- title: Google Scholar
  icon: fa fa-google
  url: https://scholar.google.com/citations?user=M3vMfZgAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_profile.png
about_content: | # this will include new lines to allow paragraphs
  Experienced Vice Chairman with a demonstrated history of working in the internet industry. 
  Skilled in <mark>Research and Development (R&D)</mark>, Matlab, Computer Vision and Algorithms. 
  Strong business development professional with a <mark>PhD</mark> focused in Electronics Engineering from İzmir Yüksek Teknoloji Enstitüsü.

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: AdresGezgini Inc.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Vice President - R&D Center Director
        caption: 2016 - Present
        quote: >
          AdresGezgini Inc. is a search engine advertising agency that provides digital marketing solutions.
        description: | # this will include new lines to allow paragraphs
            AdresGezgini Inc.'s core business areas are digital marketing solutions and web based software development projects. The sector, in which our company is located, remains as one of the brightest sectors of the future that is taking the place of traditional promotional campaigns and business management solutions, with a steady growth of over 20% every year in Turkey. Our company is in a very valuable position with its certified professional staff, its accumulated knowledge and high level of customer satisfaction that is being offered. AdresGezgini follows the latest technological trends in internet technologies with its experience and its R&D projects. By being constantly up-to date on its own workflow processes with using the latest technology, AdresGezgini offers consulting and project-based services on new internet technologies to thousands of businesses in its portfolio.
      - layout: left
        title: AdresGezgini Ltd.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Co-Founder
        caption: 2005 - 2016
        quote: >
          AdresGezgini Inc. is a search engine advertising agency that provides digital marketing solutions.
        description: | # this will include new lines to allow paragraphs
            AdresGezgini Inc.'s core business areas are digital marketing solutions and web based software development projects. The sector, in which our company is located, remains as one of the brightest sectors of the future that is taking the place of traditional promotional campaigns and business management solutions, with a steady growth of over 20% every year in Turkey. Our company is in a very valuable position with its certified professional staff, its accumulated knowledge and high level of customer satisfaction that is being offered. AdresGezgini follows the latest technological trends in internet technologies with its experience and its R&D projects. By being constantly up-to date on its own workflow processes with using the latest technology, AdresGezgini offers consulting and project-based services on new internet technologies to thousands of businesses in its portfolio.

      - layout: left
        title: İzmir Institute of Technology
        link: https://en.iyte.edu.tr/
        link_text: iyte.edu.tr
        sub_title: Research Assistant
        caption: 2004 - 2011
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          I worked as a research assistant in Electrical and Electronics Engineering Department between years 2004 and 2011. 


  - title: Teaching Experience
    layout: list
    content:
      - layout: left
        title: Yaşar University
        link: https://comp4360.github.io/
        link_text: COMP4360
        sub_title: Visiting Lecturer @ Computer Engineering Department
        caption: 2019
        quote: >
          Yaşar University is a university, in Izmir, Turkey on the Aegean Sea. The university faculty teaches in English, with programs at both the undergraduate and postgraduate level.
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.
      - layout: left
        title: İzmir Katip Çelebi University
        link: https://mee404.github.io/
        link_text: MEE404
        sub_title: Visiting Lecturer @ Mechatronics Engineering Department
        caption: 2018
        quote: >
          İzmir Kâtip Çelebi University is a public university in İzmir, Turkey, established in 2010.        
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.
      - layout: left
        title: Manisa Celal Bayar University
        link: https://www.mcbu.edu.tr/
        link_text: CSE3113
        sub_title: Visiting Lecturer @ Computer Engineering Department
        caption: 2017
        quote: >
          Manisa Celal Bayar University or is a public research university located in Manisa, Turkey. CBU traces its root back to 1959 as an independent sports and teachers' college in Manisa. The main campus is in Muradiye district of Manisa. The university is composed of 14 colleges, 3 schools, and 15 vocational schools.   
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: İzmir Institute of Technology
        caption: 2006 - 2015
        sub_title: PhD Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          [My PhD Thesis](https://openaccess.iyte.edu.tr/handle/11147/4341){:target="_blank"}
      - layout: left
        title: İzmir Institute of Technology
        caption: 2002 - 2006
        sub_title: MSc Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          [My MSc Thesis](https://openaccess.iyte.edu.tr/handle/11147/3304){:target="_blank"}
      - layout: left
        title: Middle East Technical University
        caption: 1997 - 2002
        sub_title: BSc Electrical and Electronics Engineering
        quote: >
          Middle East Technical University is a public technical university located in Ankara, Turkey. The university puts emphasis on research and education in engineering and natural sciences, offering about 40 undergraduate programs within 5 faculties, 97 masters and 62 doctorate programs within 5 graduate schools
        description: | # this will include new lines to allow paragraphs
          Lorem Ipsum
  - title: List of Journal Articles
    layout: list
    content:
      - layout: left
        sub_title:  Journal of Intelligent Information Systems
        link: https://doi.org/10.1007/s10844-020-00619-4
        link_text: DOI:10.1007/s10844-020-00619-4
        quote: > 
          Ozan, Ş. Case studies on using natural language processing techniques in customer relationship management software. J Intell Inf Syst 56, 233–253 (2021).        
        description: |
          <mark>Abstract:</mark> How can we use a text corpus stored in a customer relationship management (CRM) database for data mining and segmentation? To answer this question, we inherited the state of the art methods commonly used in natural language processing (NLP) literature, such as word embeddings, and deep learning literature, such as recurrent neural networks (RNN). We used the text notes from a CRM system taken by customer representatives of an internet ads consultancy agency between 2009 and 2020. We trained word embeddings by using the corresponding text corpus and showed that these word embeddings could be used directly for data mining and used in RNN architectures, which are deep learning frameworks built with long short-term memory (LSTM) units, for more comprehensive segmentation objectives. The obtained results prove that we can use structured text data populated in a CRM to mine valuable information. Hence, any CRM can be equipped with useful NLP features once we correctly built the problem definitions and conveniently implement the solution methods.

      - layout: left
        sub_title:  Turkish Journal of Electrical Engineering and Computer Science
        link: https://doi.org/10.3906/elk-1711-243
        link_text: DOI:10.3906/elk-1711-243
        quote: > 
          Ozan Ş , Gümüştekin Ş . Reconstruction of geometrical and reflection properties of surfaces by using structured light imaging technique. Turkish Journal of Electrical Engineering and Computer Science. 2018; 26(6): 2846-2857.
        description: |
          <mark>Abstract:</mark> When a robust and dense surface reconstruction is aimed, structured light imaging techniques are usually much appreciated. In this paper we propose a method to reconstruct both geometrical and reflective properties of surfaces by using structured light imaging. We use a technique where a camera and a projector are both treated as viewing devices. They are calibrated in the same manner. Each visible point can be correctly located on both image planes without solving a correspondence problem; hence, a dense reconstruction can be obtained. Since both the camera and the projector are explicitly calibrated, lighting and viewing directions can be identified for each surface point. It is also possible to measure reflected radiance by using high dynamic range (HDR) images for each surface point. The lighting and viewing directions that are known after calibration are combined with the reflected radiance and the incoming irradiance measurements to determine the bidirectional reflectance distribution function (BRDF) values of the material at the reconstructed surface points. We illustrate the reconstruction of surface reflection properties of sample surfaces by fitting the Phong BRDF model to the BRDF measurements.

      - layout: left
        sub_title:  Turkish Journal of Electrical Engineering and Computer Science
        link: https://doi.org/10.1016/j.dsp.2013.08.006
        link_text: DOI:10.1016/j.dsp.2013.08.006
        quote: > 
          Ozan Ş , Gümüştekin Ş . Calibration of double stripe 3D laser scanner systems using planarity and orthogonality constraints, Digital Signal Processing,2014; 24: 231-243.
        description: |
          <mark>Abstract:</mark> In this study, 3D scanning systems that utilize a pair of laser stripes are studied. Three types of scanning systems are implemented to scan environments, rough surfaces of near planar objects and small 3D objects. These scanners make use of double laser stripes to minimize the undesired effect of occlusions. Calibration of these scanning systems is crucially important for the alignment of 3D points which are reconstructed from different stripes. In this paper, the main focus is on the calibration problem, following a treatment on the pre-processing of stripe projections using dynamic programming and localization of 2D image points with sub-pixel accuracy. The 3D points corresponding to laser stripes are used in an optimization procedure that imposes geometrical constraints such as coplanarities and orthogonalities. It is shown that, calibration procedure proposed here, significantly improves the alignment of 3D points scanned using two laser stripes.
  - title: Projects
    layout: list
    content:
      - layout: left
        title: TEYDEB 1507
        sub_title: <mark>Position:</mark> Project Manager
        caption: <mark>Status:</mark> Completed
        quote: >
          TEYDEB 1507 is a public supported SME R&D Project support granted by TÜBİTAK (i.e. The Scientific and Technological Research Council of Turkey is a national agency of Turkey whose stated goal is to develop "science, technology and innovation" policies, support and conduct research and development, and to "play a leading role in the creation of a science and technology culture" in the country.)
        description: | # this will include new lines to allow paragraphs
          <mark>Project Title:</mark> DEVELOPMENT OF A SYSTEM TO DETECT FAKE CALLS BY CLASSIFYING RECORDINGS OF CALL CENTER TELEPHONE CALLS THROUGH MACHINE LEARNING 

      - layout: left
        title: TEYDEB 1501
        sub_title: <mark>Position:</mark> Project Manager
        caption: <mark>Status:</mark> Completed
        quote: >
          TEYDEB 1501 is a public supported INDUSTRY R&D Project support granted by TÜBİTAK.
        description: | # this will include new lines to allow paragraphs
          <mark>Project Title:</mark> DEVELOPMENT OF A WEB-BASED PROJECT TRACKING SYSTEM THAT CAN MAKE BUSINESS AND PROJECT TRACKING, AUTOMATICALLY ASSIGN STAFF TO TASKS, AND MAKE AUTOMATIC REPORTING  

      - layout: left
        title: TEYDEB 1501
        sub_title: <mark>Position:</mark> Project Manager
        caption: <mark>Status:</mark> Continuing
        quote: >
          TEYDEB 1501 is a public supported INDUSTRY R&D Project support granted by TÜBİTAK.
        description: | # this will include new lines to allow paragraphs
          <mark>Project Title:</mark> GENERAL PURPOSE CHATBOT APPLICATION THAT CAN PRODUCE MEANINGFUL DIALOGUE WITH MACHINE LEARNING

      - layout: left
        title: TEYDEB 1501
        sub_title: <mark>Position:</mark> Project Manager
        caption: <mark>Status:</mark> Continuing
        quote: >
          TEYDEB 1501 is a public supported INDUSTRY R&D Project support granted by TÜBİTAK.
        description: | # this will include new lines to allow paragraphs
          <mark>Project Title:</mark> DEVELOPMENT OF THE SYSTEM THAT PROVIDES THE AUTOMATIC DETECTION OF NEGATIVE CALL CENTER INTERVIEWS WITH DEEP ARTIFICIAL NEURAL NETWORKS BASED CLASSIFICATION ALGORITHMS

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag