# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Şükrü Ozan, Ph.D.
title: Vice Chairman, R&D Center Director
email: sukruozan@gmail.com
website: http://www.sukruozan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sukruozan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sukruozan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Şükrü Ozan @ AdresGezgini Inc.
  icon: fas fa-globe
  url: https://www.adresgezgini.com/ekibimiz/sukru-ozan
- title: Google Scholar
  icon: fa fa-google
  url: https://scholar.google.com/citations?user=M3vMfZgAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_profile.png
about_content: | # this will include new lines to allow paragraphs
  Experienced Vice Chairman with a demonstrated history of working in the internet industry. 
  Skilled in <mark>Research and Development (R&D)</mark>, Matlab, Computer Vision and Algorithms. 
  Strong business development professional with a <mark>PhD</mark> focused in Electronics Engineering from İzmir Yüksek Teknoloji Enstitüsü.

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: AdresGezgini Inc.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Vice President - R&D Center Director
        caption: 2016 - Present
        quote: >
          AdresGezgini Inc. is a search engine advertising agency that provides digital marketing solutions.
        description: | # this will include new lines to allow paragraphs
            AdresGezgini Inc.'s core business areas are digital marketing solutions and web based software development projects. The sector, in which our company is located, remains as one of the brightest sectors of the future that is taking the place of traditional promotional campaigns and business management solutions, with a steady growth of over 20% every year in Turkey. Our company is in a very valuable position with its certified professional staff, its accumulated knowledge and high level of customer satisfaction that is being offered. AdresGezgini follows the latest technological trends in internet technologies with its experience and its R&D projects. By being constantly up-to date on its own workflow processes with using the latest technology, AdresGezgini offers consulting and project-based services on new internet technologies to thousands of businesses in its portfolio.
      - layout: left
        title: AdresGezgini Ltd.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Co-Founder
        caption: 2005 - 2016
        quote: >
          AdresGezgini Inc. is a search engine advertising agency that provides digital marketing solutions.
        description: | # this will include new lines to allow paragraphs
            AdresGezgini Inc.'s core business areas are digital marketing solutions and web based software development projects. The sector, in which our company is located, remains as one of the brightest sectors of the future that is taking the place of traditional promotional campaigns and business management solutions, with a steady growth of over 20% every year in Turkey. Our company is in a very valuable position with its certified professional staff, its accumulated knowledge and high level of customer satisfaction that is being offered. AdresGezgini follows the latest technological trends in internet technologies with its experience and its R&D projects. By being constantly up-to date on its own workflow processes with using the latest technology, AdresGezgini offers consulting and project-based services on new internet technologies to thousands of businesses in its portfolio.

      - layout: left
        title: İzmir Institute of Technology
        link: https://en.iyte.edu.tr/
        link_text: iyte.edu.tr
        sub_title: Research Assistant
        caption: 2004 - 2011
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          I workder as a research assistant in Electrical and Electronics Engineering Department between years 2004 and 2011. 


  - title: Teaching Experience
    layout: list
    content:
      - layout: left
        title: Yaşar University
        link: https://comp4360.github.io/
        link_text: COMP4360
        sub_title: Visiting Lecturer @ Computer Engineering Department
        caption: 2019
        quote: >
          Yaşar University is a university, in Izmir, Turkey on the Aegean Sea. The university faculty teaches in English, with programs at both the undergraduate and postgraduate level.
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.
      - layout: left
        title: İzmir Katip Çelebi University
        link: https://mee404.github.io/
        link_text: MEE404
        sub_title: Visiting Lecturer @ Mechatronics Engineering Department
        caption: 2018
        quote: >
          İzmir Kâtip Çelebi University is a public university in İzmir, Turkey, established in 2010.        
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.
      - layout: left
        title: Manisa Celal Bayar University
        link: https://www.mcbu.edu.tr/
        link_text: CSE3113
        sub_title: Visiting Lecturer @ Computer Engineering Department
        caption: 2017
        quote: >
          Manisa Celal Bayar University or is a public research university located in Manisa, Turkey. CBU traces its root back to 1959 as an independent sports and teachers' college in Manisa. The main campus is in Muradiye district of Manisa. The university is composed of 14 colleges, 3 schools, and 15 vocational schools.   
        description: | # this will include new lines to allow paragraphs
          The aim of COMP4360s is to provide an introduction to image processing. The course demonstrates the low and mid-level vision techniques such as filtering in the spatial and frequency domain, image enhancement, edge detection, image segmentation, image compression and their applications. We will not stick with a unique text book, but it is recommended to have the book below in your library, if you are interested in image processing literature. We will be using Python programming language. The exact version is Python 3.6.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: İzmir Institute of Technology
        caption: 2006 - 2015
        sub_title: PhD Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          [My PhD Thesis](https://openaccess.iyte.edu.tr/handle/11147/4341){:target="_blank"}
      - layout: left
        title: İzmir Institute of Technology
        caption: 2002 - 2006
        sub_title: MSc Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          [My MSc Thesis](https://openaccess.iyte.edu.tr/handle/11147/3304){:target="_blank"}
      - layout: left
        title: Middle East Technical University
        caption: 1997 - 2002
        sub_title: BSc Electrical and Electronics Engineering
        quote: >
          Middle East Technical University is a public technical university located in Ankara, Turkey. The university puts emphasis on research and education in engineering and natural sciences, offering about 40 undergraduate programs within 5 faculties, 97 masters and 62 doctorate programs within 5 graduate schools
        description: | # this will include new lines to allow paragraphs
          [My MSc Thesis](https://openaccess.iyte.edu.tr/handle/11147/3304)          

  - title: Publications
    layout: default
    content:
      - layout: default
        title: Case studies on using natural language processing techniques in customer relationship management software
        authors: Şükrü Ozan
        publication: Journal of Fancy Research
        year: 2021
        doi: http://dx.doi.org/XX.XXX/


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag