# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Şükrü Ozan, Ph.D.
title: Vice Chairman, R&D Center Director
email: sukruozan@gmail.com
website: http://www.sukruozan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  sukruozan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: sukruozan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Şükrü Ozan @ AdresGezgini Inc.
  icon: fas fa-globe
  url: https://www.adresgezgini.com/ekibimiz/sukru-ozan
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_profile.png
about_content: | # this will include new lines to allow paragraphs
  Experienced Vice Chairman with a demonstrated history of working in the internet industry. 
  Skilled in <mark>Research and Development (R&D)</mark>, Matlab, Computer Vision and Algorithms. 
  Strong business development professional with a <mark>PhD</mark> focused in Electronics Engineering from İzmir Yüksek Teknoloji Enstitüsü.

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: AdresGezgini Inc.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Vice President - R&D Center Director
        caption: 2015 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Teaching Experience
    layout: list
    content:
      - layout: left
        title: AdresGezgini Inc.
        link: https://www.adresgezgini.com/en/
        link_text: adresgezgini.com
        sub_title: Vice President - R&D Center Director
        caption: 2015 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: İzmir Institute of Technology
        caption: 2006 - 2015
        sub_title: PhD Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          ![My PhD Thesis](https://openaccess.iyte.edu.tr/handle/11147/4341)
      - layout: left
        title: İzmir Institute of Technology
        caption: 2002 - 2006
        sub_title: MSc Electrical and Electronics Engineering
        quote: >
          İzmir Institute of Technology is a public research university in İzmir, Turkey. İYTE maintains a strong emphasis on the natural sciences and engineering and is the only institute of its kind in Turkey with a special focus on scientific research
        description: | # this will include new lines to allow paragraphs
          ![My MSc Thesis](https://openaccess.iyte.edu.tr/handle/11147/3304)
      - layout: left
        title: Middle East Technical University
        caption: 1997 - 2002
        sub_title: BSc Electrical and Electronics Engineering
        quote: >
          Middle East Technical University is a public technical university located in Ankara, Turkey. The university puts emphasis on research and education in engineering and natural sciences, offering about 40 undergraduate programs within 5 faculties, 97 masters and 62 doctorate programs within 5 graduate schools
        description: | # this will include new lines to allow paragraphs
          ![My MSc Thesis](https://openaccess.iyte.edu.tr/handle/11147/3304)          


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag